services:
  postgres-db:
    image: postgres:latest
    container_name: postgres_code_baron
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    # volumes:
      # - postgres_data:/var/lib/postgres
  

  # ! <--- AI TOOLS ---> !
  ollama:
    ports:
      - 11434:11434
    container_name: ollama
    image: ollama/ollama:latest
    hostname: ollama
    networks:
      mynetwork:

  ollama-webui:
    ports:
      - 3000:8080
    container_name: ollama-webui
    restart: always
    image: ghcr.io/open-webui/open-webui:cuda
    hostname: ollama-webui
    networks:
      mynetwork:

networks:
  mynetwork:
    driver: bridge